version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/node:7.10    #  $check node -v
      - image: circleci/node:8.10.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm  install
      - run: yarn test
